branches:
  except:
    - draft
    - tmp
    - /.*\.(draft|tmp)$/
    - /^(draft|tmp)\..*/

language: rust
rust: stable

env:
  - DENO_VERSION=v0.40.0

cache:
  directories:
    # Rust
    - $HOME/.cache/sccache
    - $HOME/.cargo
    - $HOME/.rustup
    - target

    # Deno
    - $HOME/.cache/deno

    # Node.js
    - $HOME/.pnpm-store
    - $HOME/.node-gyp
    - $HOME/.node_libraries

addons:
  apt:
    packages:
      - make

before_cache:
  - rm -rf $HOME/.cargo/registry/src

before_install:
  # Install Deno
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
  - sudo ln -s "$HOME/.deno/bin/deno" /bin/deno

  # Install wasm-pack
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

script:
  - make lib
  - deno run -A run-tests.ts
